
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import { logo } from "../assets/icons";
import { BG, Gradient } from "../assets/images";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <div className={`w-screen h-[100dvh] flex flex-col items-center overflow-hidden relative ${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Image src={logo} alt="logo" className="absolute left-10 top-10 w-32"/>
            <Image src={BG} alt="auth-bg" className="absolute object-cover size-full top-0 left-0"/>
            <Image src={Gradient} alt="gradient-bg" className="absolute object-cover w-full top-0"/>

            <div className="size-full flex flex-col items-center justify-center z-10">
                {children}
            </div>
        </div>
    );
}
